language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t eppifoss/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true eppifoss/react-test npm test 

after_success:
  - docker build -t eppifoss/multi-client  ./client
  - docker build -t eppifoss/multi-server  ./server
  - docker build -t eppifoss/multi-worker  ./worker
  - docker build -t eppifoss/multi-nginx  ./nginx

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push images to docker hub
  - docker push eppifoss/multi-client 
  - docker push eppifoss/multi-server 
  - docker push eppifoss/multi-worker
  - docker push eppifoss/multi-nginx

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-west-2
  app: multi-docker
  env: MultiDocker-env 
  bucket_name: elasticbeanstalk-us-west-2-476578251364
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
